# Generated by Django 3.2.7 on 2024-03-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lesson',
            field=models.CharField(default='lesson_1', max_length=200),
        ),
    ]
